### ISSUE TITLE
Transform point in one image to another

### ISSUE THREAD

**Issue by chaiban** [JiahaoPlus/camera-calibration#1]
Hi @JiahaoPlus , 

Your code is very helpful. 

Do you have any idea on how I can get point in one camera image to another ? 

Know parameters: Transformation from Board to Camera 1 
                              Transformation from Board to Camera 2 

I need to find transformation from camera 2 to camera 1. So I did inverse(B to C2) * (B to C1). but the translation is wrong. DO you have any idea ? 

Thank you

**Comment by JiahaoPlus** [comment]
Hi @chaiban ,

Thanks for your question. Are you using homogeneous transformation? If yes, I guess (B to C1) * inverse(B to C2) is what you need. 

p_{C1}  =  H_{C2}^{C1}  *  p_{C2}
=  H_B^{C1}  *  H_{C2}^B  *  p_{C2}

p_{C1}: point in C1
p_{C2}: point in C2
H_{C2}^{C1}: homogeneous transformation from C2 to C1
H_B^{C1}: homogeneous transformation from B to C1
H_{C2}^B: homogeneous transformation from C2 to B

Cheers

**Comment by chaiban** [comment]
HI @JiahaoPlus ,
Thank you for the clarification. 

Even with that I could not get the right values. You can see the output in the below figure.
![Capture](https://user-images.githubusercontent.com/38505021/72805846-1a09f100-3c54-11ea-997a-fd73220e5f39.PNG)

Just in case I am also attaching the code I wrote to get  the transformation.
![Capture2](https://user-images.githubusercontent.com/38505021/72805955-62291380-3c54-11ea-8526-303a62b2f716.PNG)

Finally, the transformation is multiplied with a point in camera 2 coordinates to get the point in camera 1 coordinates. But I am not sure where the issue is ? can you please clarify if you can ?

Thank you!
